### ISSUE TITLE
Fields in 'modify' dialog disappear if they be emptied

### ISSUE THREAD

**Issue by SvenBunge** [holisticon/flynn-book-scanner#72]
Steps to reproduce:
1. Select a book and open the 'modify' dialog
2. remove all characters from the 'owner'-Field (to enter a different one)
3. Bug: Field disappears

Workaround: Type new value first and remove old stuff later on.

Environment: Nexus 5, Android 4.4, Flynn 1.3.2build125

**Comment by hypery2k** [comment]
already fixed by a4e95f825896f8d3c5d467a415afef30707dca0d
Please use new [PlayStore App](https://play.google.com/apps/testing/de.holisticon.app.flynn). It can be installed in parallel to the older one, as it uses a new AppID, see 4e3f1f1788bae7a9fe8d8c78ebf8c744f6dd92db

With 1.3.5build142 I cannot reproduce the error

**Comment by SvenBunge** [comment]
Thanks, the update fixed the issue for me. :+1:
